### ISSUE TITLE
Mity merge - IndexError: list index out of range

### ISSUE THREAD

**Issue by anjalijain22** [KCCG/mity#12]
Hi, 
I'm running into the below IndexError with `mity merge`:
> mity 0.3.0
mity vcf merge
Traceback (most recent call last):
  File "/home/ajain/.local/bin/mity", line 29, in <module>
    args.func(args)
  File "/home/ajain/.local/lib/python3.9/site-packages/mitylib/commands.py", line 191, in _cmd_merge
    merge.do_merge(args.mity_vcf, args.nuclear_vcf, args.prefix, genome)
  File "/home/ajain/.local/lib/python3.9/site-packages/mitylib/merge.py", line 139, in do_merge
    mity_number = mity_line.split("Number=")[1]
IndexError: list index out of range

The command I'm using is - `mity merge --prefix combined --mity_vcf file.mity.vcf.gz --nuclear_vcf file_nuclear.vcf.gz` in which the file.mity.vcf.gz file was generated using the `mity call` function. 

I'd really appreciate your help on how to resolve this error. Thanks in advance!

**Comment by drmjc** [comment]
Hi, what nuclear variant caller did you use? I think it's failing on a line that's specific for GATK HaplotypeCaller. Thanks

**Comment by anjalijain22** [comment]
Thanks for your reply!
Yes, I used the GATK HaplotypeCaller. What would be the workaround for this?

**Comment by drmjc** [comment]
Hi,
It looks like the format of mity_line is unexpected.
Can you share both vcf files? I only need the header lines and a small
number of variants.
Thanks

**Comment by anjalijain22** [comment]
Sure, here are the nuclear and mity vcf files -
[sample_mity.vcf.gz](https://github.com/KCCG/mity/files/8273317/sample_mity.vcf.gz)
[sample_nuclear.vcf.gz](https://github.com/KCCG/mity/files/8273318/sample_nuclear.vcf.gz)

**Comment by trentzz** [comment]
Hi, the issues you've mentioned should be resolved in the new release of Mity 1.1.0. If you encounter any further problems, please feel free to open a new issue. Thanks!
