### ISSUE TITLE
unable to find FASTA index entry for 'chrM'\n"

### ISSUE THREAD

**Issue by vaishmanobala** [KCCG/mity#16]
I'm using mity via docker to run the script
`docker run -w "$PWD" -v "$PWD":"$PWD" drmjc/mity call --prefix chrM --out-folder-path test_out  --normalise test_in/INDKAA23695_RE5_BS_TO.bam`
freebayes tool couldn'r recognise fasta index
`Found dependency: /usr/local/bin/freebayes
Found dependency: /usr/local/bin/gsort
Found dependency: /usr/local/bin/tabix
Found dependency: /usr/local/bin/bgzip
Found dependency: /usr/local/bin/python
Found dependency: /usr/local/bin/mity
mity version 0.3.0
Calling mitochondrial variants
Running FreeBayes in sensitive mode
FreeBayes failed: b"unable to find FASTA index entry for 'chrM'\n"`

Need help!!

TIA

**Comment by drmjc** [comment]
Hi, Are you sure the mito contig is called chrM in your BAM? try `samtools view -H test_in/INDKAA23695_RE5_BS_TO.bam | grep -e chrM -e MT`

**Comment by dridk** [comment]
which genome version should we use ?

**Comment by MatDaw** [comment]
Hi, I've stumbled upon same error as @vaishmanobala. BAM file was aligned to hg38 and samtools returned chrM as the name of the contig. Specifing reference genome with `--reference hg38` solved the issue. I'm using 0.4.0 docker version of mity.

**Comment by trentzz** [comment]
Hi, the issues you've mentioned should be resolved in the new release of Mity 1.1.0. If you encounter any further problems, please feel free to open a new issue. Thanks!
