### ISSUE TITLE
hg38 auxiliary data

### ISSUE THREAD

**Issue by holtjma** [KCCG/mity#2]
Hello, I ran `mity` on some hg38 dataset, but the end result appeared to be missing many annotations (I compared to the exact same dataset run with the hs37d5 MT).  The variants were mostly the same although there were 11/34 missing from the hg38 run.  Is there something I'm doing wrong?

**Comment by drmjc** [comment]
Thank you for this report. I have done less testing with hg38, so it could be at our end. Is solving this still of interest to you?
thanks

**Comment by holtjma** [comment]
In general, yes I'm still interested in mity.  I would need to dig up where I did the original test if you need some info from me, since it's been a while.

**Comment by drmjc** [comment]
Hi @holtjma, v0.2.1 has fixed this. If there's any dramas, please let me know
