### ISSUE TITLE
cram for mm10

### ISSUE THREAD

**Issue by AhmedArslan** [KCCG/mity#21]
Hi, I know cram file supported have been added (https://github.com/KCCG/mity/issues/6) but when I am running mity on cram files for mm10 and getting the following error. 

mity call --reference mm10 --prefix CH --out-folder-path CH.cram  --region chrMT:1-16299 --normalise 
mity version 0.4.0 
Calling mitochondrial variants Running 
FreeBayes in sensitive mode 
FreeBayes failed: b'ERROR(freebayes): Could not open input BAM files\nBamMultiReader::Open: unable to open all files: \t\n\tunable to open file: CH.cram\n\n'

**Comment by drmjc** [comment]
Hi,
I've never tried this combination (of mm10 and cram), but let's start with the command. can you try:

```
mity call --reference mm10 --prefix CH --out-folder-path ./CH_results/ --region chrMT:1-16299 --normalise CH.cram
```
thanks

**Comment by AhmedArslan** [comment]
Thanks, it did work, eventually.
