### ISSUE TITLE
How long would 1072 WGS sample data take?

### ISSUE THREAD

**Issue by Qinqiword** [KCCG/mity#4]
Hi,

I have 1072 whole blood samples that have a WGS sequencing depth of 30X. 
I was running `mity`  call  their mitochondrial mutations. An error occurred when they continued to run to the 1243 hour. The running code and log are as follows:

`mity call  --prefix wjp_chrM --reference hg38 --out-folder-path mity_out --normalise  1.bam 2.bam 3.bam 4.bam 5.bam 6.bam ... 1071.bam 1072.bam #(Ellipsis: bam names of 1072 samples)`

the log.txt:
```
mity version 0.1.3
Calling mitochondrial variants
Running FreeBayes in sensitive mode
=>> PBS: job killed: walltime 5400001 exceeded limit 5400000
```

And only the  one file  `wjp_chrM_1072.unnormalised.vcf.gz` was generated before the program terminated.

Therefore, I have three questions that I would like to ask:
**1. For 1072 WGS samples, how long does it take to use mity call mutation? , Is there a more efficient way?**
**2. For the error message `walltime 5400001 exceeded limit 5400000`, what caused it?**
**3. Has the generated wjp_chrM_1072.unnormalised.vcf.gz file completed the call mutation steps? Can I use this result file to normalize myself with bcftools?**

In addition, I tried to run `mity` with only **ten samples**, which is successful, but fails when using **1072 samples**.

Any comments or suggestions would be appreciated.

best,
qinqi

**Comment by drmjc** [comment]
Hi, sorry I missed your ticket.
I've never tried batches that large & there's no 'joint calling' benefit from analysing so many samples in one batch. So the simplest solution is to use smaller batches of say 100. Then just combine the VCF files together using one of many tools. The walltime limit sounds like a limit imposed in your computing environment, as there are no such limits in mity itself.
best, Mark
