### ISSUE TITLE
report-config.yaml missing

### ISSUE THREAD

**Issue by kkNGSKOCMG** [KCCG/mity#43]
mity call seem to work fine but I get the following error message after running mity report.

call

docker run -w "$PWD" -v "$PWD":"$PWD" drmjc/mity call --normalise HG002.hs37d5.2x250.small.MT.RG.bam
This was fine and 
HG002.hs37d5.2x250.small.MT.RG.normalise.vcf.gz
was created.

Then I ran

Docker run -w "$PWD" -v "$PWD":"$PWD" drmjc/mity report HG002.hs37d5.2x250.small.MT.RG.normalise.vcf.gz
mity 1.0.0

I got the following error messages.

mity 1.0.0
Generating mity report
Traceback (most recent call last):
  File "/usr/local/bin/mity", line 33, in <module>
    main()
  File "/usr/local/bin/mity", line 29, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/mitylib/commands.py", line 247, in _cmd_report
    report.Report(
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 447, in __init__
    self.run()
  File "/usr/local/lib/python3.10/site-packages/mitylib/report.py", line 463, in run
    self.output_dir, self.prefix + ".annotated_variants.xlsx"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Please help.

**Comment by kkNGSKOCMG** [comment]
(continued)

The above error was partially resolved by changing
report.py" as below.

xlsx_name = os.path.join(
self.output_dir, self.prefix + ".annotated_variants.xlsx"
)
 to       
        xlsx_name = "annotated_variants.xlsx"

However,  
the following error appeared thereafter.

lib/python3.7/site-packages/mitylib/report.py", line 179, in __init__
    with open("report-config.yaml", "r") as report_config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'report-config.yaml'

Can you provide 
report-config.yaml
?

**Comment by RogueRussell** [comment]
@kkNGSKOCMG I had this issue as well and was able to resolve it so hopefully this helps you too. I manually downloaded the report-config.yaml from github (https://github.com/KCCG/mity/blob/master/mitylib/report-config.yaml). Then I put it in the mitylib file of my own download. That MIGHT work for you. It didn't for me. It still couldn't find it. So I manually edited the report.py file myself to direct it to the absolute path of the config file and that worked. Should look something like this: 
# Define the absolute path to the configuration file
        report_config_path = "youraboslutepath/mitylib/report-config.yaml"

        # Open the configuration file using the absolute path
        with open(report_config_path, "r") as report_config_file:
            self.report_config = yaml.safe_load(report_config_file)

So hopefully that authors will fix this but in the meantime, this worked for me.

**Comment by drmjc** [comment]
thanks for reporting this. @trentzz can you please look into resolving this?

**Comment by christianfares** [comment]
Hi @kkNGSKOCMG and @RogueRussell we have updated mity to no longer require you to have the report-config.yaml file located in your current directory. With version 1.1.0 mity uses the default config found here: https://github.com/KCCG/mity/blob/master/mitylib/config/report-config.yaml

**Comment by RogueRussell** [comment]
Just tested it with mity 1.1.0 and it found the config files. Thanks for checking this out and fixing it! Much appreciated
