### ISSUE TITLE
Annotation files with different chr notations

### ISSUE THREAD

**Issue by RogueRussell** [KCCG/mity#44]
I've been trying to run mity report on my vcf that I called with mity call. However, there are no results in the excel file that correspond to the vcfanno step. Looking further into it, it appears that the files provided in mitylib/annot/ that vcfanno references all use the MT chr notation. My VCFs are build 38 so use the chrM notation and this is presumably why vcfanno is not able to properly annotate the file.

Annotations for build38 (which use chrM notation) should be added to the annot/ folder. Or at least should be mentioned somewhere that the annotations are only for MT to eliminate confusion.

Thanks.

**Comment by drmjc** [comment]
Thanks for reporting this issue. When mity didn't use vcfanno, it was
robust to this, so we'll aim to do the same.

Trent can you please add this to the list? There at least three solutions
1 duplicate all the annotations with the chrM contig
2 see if vcfanno handles contig aliases (as both are equivalent in version
38 of the ref genome. Note they were not equivalent in hg19 and grch37)
3 swap the contig name in the vcf before running vcfanno, and then back
again in the xls file

If the annotations are still small then option 1 is ok, but it seems
wasteful.

Cheers, Mark

**Comment by christianfares** [comment]
Hi @RogueRussell we have just pushed an update to mity which adds chrM annotations. mity version 1.1.0.
We added a new config option `--contig [MT|chrM]` to allow you to select which version of the annotations you want to use.
Please have another crack at it and let use know if it works now 🙂

**Comment by RogueRussell** [comment]
Just tried the --contig option with mity 1.1.0 and it worked great! Thanks so much for looking into this and adding the feature.

However, a note with the new version of mity 1.1.0. On line 496 of report.py, it uses the "match" feature of python. I believe this feature of python requires Python 3.10 or newer. I could not run mity 1.1.0 until I updated my Python from 3.8 to 3.11. The dependencies listed in the readme just say python3(tested on 3.7.4). Perhaps listing Python>3.10 as a dependency would help others.

Thanks again for your help!

**Comment by trentzz** [comment]
Hi @RogueRussell, glad the new release version is working well for you! Thanks for the suggestion, I'm planning on updating and adding new documentation for mity in the next release, so I'll definitely update the python version notes when that happens. 

I'll close this issue now, but feel free to open a new one if you encounter any other issues or have any feature recommendations. Thanks!
